import React from 'react';

const TermsAndConditions = () => {
  const containerStyle = {
    maxWidth: '800px',
    margin: '0 auto',
    padding: '40px 20px',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    lineHeight: '1.6',
    color: '#333',
    backgroundColor: '#fff'
  };

  const headerStyle = {
    textAlign: 'center',
    marginBottom: '40px',
    borderBottom: '2px solid #e0e0e0',
    paddingBottom: '20px'
  };

  const titleStyle = {
    fontSize: '2.5rem',
    fontWeight: '700',
    color: '#2c3e50',
    marginBottom: '10px'
  };

  const lastUpdatedStyle = {
    fontSize: '0.9rem',
    color: '#666',
    fontStyle: 'italic'
  };

  const sectionStyle = {
    marginBottom: '30px'
  };

  const sectionTitleStyle = {
    fontSize: '1.4rem',
    fontWeight: '600',
    color: '#34495e',
    marginBottom: '15px',
    borderLeft: '4px solid #3498db',
    paddingLeft: '15px'
  };

  const subsectionTitleStyle = {
    fontSize: '1.1rem',
    fontWeight: '600',
    color: '#2c3e50',
    marginTop: '20px',
    marginBottom: '10px'
  };

  const paragraphStyle = {
    marginBottom: '15px',
    textAlign: 'justify'
  };

  const listStyle = {
    paddingLeft: '20px',
    marginBottom: '15px'
  };

  const listItemStyle = {
    marginBottom: '8px'
  };

  const contactStyle = {
    backgroundColor: '#f8f9fa',
    padding: '20px',
    borderRadius: '8px',
    border: '1px solid #e9ecef',
    textAlign: 'center',
    marginTop: '40px'
  };

  const emailLinkStyle = {
    color: '#3498db',
    textDecoration: 'none',
    fontWeight: '500'
  };

  return (
    <div style={containerStyle}>
      <div style={headerStyle}>
        <h1 style={titleStyle}>Terms and Conditions for Inspo AI</h1>
        <p style={lastUpdatedStyle}>Last Updated: May 27, 2025</p>
      </div>

      <div style={sectionStyle}>
        <h2 style={sectionTitleStyle}>1. Introduction</h2>
        <p style={paragraphStyle}>
          Welcome to Inspo AI ("we," "our," or "us"). These Terms and Conditions ("Terms") govern your access to and use of the Inspo AI website, applications, and services (collectively, the "Service").
        </p>
        <p style={paragraphStyle}>
          By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the Terms, you may not access the Service.
        </p>
      </div>

      <div style={sectionStyle}>
        <h2 style={sectionTitleStyle}>2. Definitions</h2>
        <ul style={listStyle}>
          <li style={listItemStyle}><strong>"Content"</strong> refers to all text, images, graphics, photos, audio, video, information, or other materials that you upload, submit, or provide through the Service.</li>
          <li style={listItemStyle}><strong>"Moodboard"</strong> refers to the visual collections of images, colors, and design elements generated by our AI technology based on your inputs.</li>
          <li style={listItemStyle}><strong>"User"</strong> refers to any individual who accesses or uses the Service.</li>
        </ul>
      </div>

      <div style={sectionStyle}>
        <h2 style={sectionTitleStyle}>3. Account Registration</h2>
        <p style={paragraphStyle}>
          To access certain features of the Service, you may be required to register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete.
        </p>
        <p style={paragraphStyle}>
          You are responsible for safeguarding your password and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.
        </p>
      </div>

      <div style={sectionStyle}>
        <h2 style={sectionTitleStyle}>4. Subscription and Payments</h2>
        
        <h3 style={subsectionTitleStyle}>4.1 Free Tier</h3>
        <p style={paragraphStyle}>
          Inspo AI offers a free tier with limited features. The specifics of the free tier, including usage limits, are subject to change at our discretion.
        </p>

        <h3 style={subsectionTitleStyle}>4.2 Paid Subscriptions</h3>
        <p style={paragraphStyle}>
          We offer paid subscription plans that provide access to additional features. By subscribing to a paid plan, you agree to pay the fees indicated for your selected subscription. All payments are processed through our third-party payment processors.
        </p>

        <h3 style={subsectionTitleStyle}>4.3 Billing and Renewal</h3>
        <p style={paragraphStyle}>
          Subscriptions are billed on a recurring basis (monthly or annually, depending on your selection). Your subscription will automatically renew unless you cancel it before the renewal date.
        </p>

        <h3 style={subsectionTitleStyle}>4.4 Cancellation and Refunds</h3>
        <p style={paragraphStyle}>
          You may cancel your subscription at any time through your account settings. Cancellations will take effect at the end of your current billing period. We do not provide refunds for the unused portion of your subscription period unless required by law.
        </p>
      </div>

      <div style={sectionStyle}>
        <h2 style={sectionTitleStyle}>5. Intellectual Property</h2>
        
        <h3 style={subsectionTitleStyle}>5.1 Our Intellectual Property</h3>
        <p style={paragraphStyle}>
          The Service and its original content (excluding Content provided by users), features, and functionality are and will remain the exclusive property of Inspo AI and its licensors. The Service is protected by copyright, trademark, and other laws.
        </p>

        <h3 style={subsectionTitleStyle}>5.2 User Content</h3>
        <p style={paragraphStyle}>
          When you upload, submit, or provide Content to the Service, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such Content throughout the world in any media.
        </p>

        <h3 style={subsectionTitleStyle}>5.3 Moodboards and Generated Content</h3>
        <p style={paragraphStyle}>
          <strong>5.3.1 License to Generated Content:</strong> Inspo AI grants you a non-exclusive, worldwide license to use the moodboards and other content generated by our Service for your personal or commercial purposes.
        </p>
        <p style={paragraphStyle}>
          <strong>5.3.2 Limitations on Generated Content:</strong> Some images included in moodboards may be sourced from third parties. We make no representations or warranties regarding your right to use these images beyond the moodboard context. If you wish to use individual images commercially, you should verify their licensing requirements independently.
        </p>
      </div>

      <div style={sectionStyle}>
        <h2 style={sectionTitleStyle}>6. User Guidelines</h2>
        
        <h3 style={subsectionTitleStyle}>6.1 Prohibited Uses</h3>
        <p style={paragraphStyle}>You agree not to use the Service to:</p>
        <ul style={listStyle}>
          <li style={listItemStyle}>Generate, upload, or share content that is illegal, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable</li>
          <li style={listItemStyle}>Impersonate any person or entity or falsely state or misrepresent your affiliation with a person or entity</li>
          <li style={listItemStyle}>Interfere with or disrupt the Service or servers or networks connected to the Service</li>
          <li style={listItemStyle}>Attempt to gain unauthorized access to parts of the Service</li>
          <li style={listItemStyle}>Use automated scripts or bots to access the Service, except as specifically permitted via official APIs</li>
          <li style={listItemStyle}>Collect or harvest user data without permission</li>
          <li style={listItemStyle}>Generate content that infringes upon intellectual property rights, privacy rights, or other rights of any party</li>
        </ul>

        <h3 style={subsectionTitleStyle}>6.2 Content Moderation</h3>
        <p style={paragraphStyle}>
          We reserve the right, but not the obligation, to monitor and moderate all Content. We may remove or refuse to display content that we believe violates these Terms or may harm our users, the Service, or third parties.
        </p>
      </div>

      <div style={sectionStyle}>
        <h2 style={sectionTitleStyle}>7. Third-Party Services and Links</h2>
        <p style={paragraphStyle}>
          The Service may contain links to third-party websites or services that are not owned or controlled by Inspo AI. We have no control over, and assume no responsibility for, the content, <a href="https://app.inspoai.live/privacy-policy">privacy policies</a>
, or practices of any third-party websites or services.
        </p>
      </div>

      <div style={sectionStyle}>
        <h2 style={sectionTitleStyle}>8. Data Usage and AI Training</h2>
        
        <h3 style={subsectionTitleStyle}>8.1 Service Improvement</h3>
        <p style={paragraphStyle}>
          We may use anonymized user queries and interactions to improve our AI models and Service. This helps us enhance the quality and relevance of generated moodboards.
        </p>

        <h3 style={subsectionTitleStyle}>8.2 Opt-Out</h3>
        <p style={paragraphStyle}>
          Users may opt out of having their data used for AI improvement purposes by contacting us at <a href="mailto:inspoai.live@gmail.com" style={emailLinkStyle}>inspoai.live@gmail.com</a>.
        </p>
      </div>

      <div style={sectionStyle}>
        <h2 style={sectionTitleStyle}>9. Limitation of Liability</h2>
        <p style={paragraphStyle}>
          To the maximum extent permitted by law, in no event shall Inspo AI, its affiliates, officers, directors, employees, or agents be liable for any indirect, punitive, incidental, special, consequential, or exemplary damages, including without limitation damages for loss of profits, goodwill, use, data, or other intangible losses, arising out of or relating to the use of, or inability to use, the Service.
        </p>
      </div>

      <div style={sectionStyle}>
        <h2 style={sectionTitleStyle}>10. Disclaimer of Warranties</h2>
        <p style={paragraphStyle}>
          The Service is provided on an "AS IS" and "AS AVAILABLE" basis. Inspo AI expressly disclaims all warranties of any kind, whether express or implied, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
        </p>
      </div>

      <div style={sectionStyle}>
        <h2 style={sectionTitleStyle}>11. Indemnification</h2>
        <p style={paragraphStyle}>
          You agree to defend, indemnify, and hold harmless Inspo AI and its licensors, service providers, and affiliates from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees arising out of or relating to your use of the Service or your breach of these Terms.
        </p>
      </div>

      <div style={sectionStyle}>
        <h2 style={sectionTitleStyle}>12. Modifications to the Service and Terms</h2>
        <p style={paragraphStyle}>
          We reserve the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. We may also modify these Terms from time to time. The revised Terms will be effective immediately upon posting. Your continued use of the Service after any modification to the Terms constitutes your acceptance of the revised Terms.
        </p>
      </div>

      <div style={sectionStyle}>
        <h2 style={sectionTitleStyle}>13. Termination</h2>
        <p style={paragraphStyle}>
          We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach these Terms.
        </p>
      </div>

      <div style={sectionStyle}>
        <h2 style={sectionTitleStyle}>14. Governing Law</h2>
        <p style={paragraphStyle}>
          These Terms shall be governed by and construed in accordance with the laws of [Jurisdiction], without regard to its conflict of law provisions.
        </p>
      </div>

      <div style={contactStyle}>
        <h2 style={sectionTitleStyle}>15. Contact Us</h2>
        <p style={paragraphStyle}>
          If you have any questions about these Terms, please contact us at{' '}
          <a href="mailto:inspoai.live@gmail.com" style={emailLinkStyle}>
            inspoai.live@gmail.com
          </a>
        </p>
      </div>
    </div>
  );
};

export default TermsAndConditions;
